package backend.gamification.enumkey.user;

public enum RegisterEnum {
    Token_REGISTER,
    Result_REGISTER,
    Success_REGISTER,
    Information_REGISTER,
    Error_REGISTER,
    Contract_Error_REGISTER,
    Username_Error_REGISTER,
    Email_Error_REGISTER,
    Phone_Error_REGISTER,
    Password_Error_REGISTER,
    Information_Missing_Error_REGISTER,
    Unknown_Class_Error_REGISTER,
    Username_Success_REGISTER,
    Email_Success_REGISTER,
    Phone_Success_REGISTER,
    Password_Success_REGISTER,
    Name_Success_REGISTER,
    Dob_Success_REGISTER,
    Address_Success_REGISTER,
    Identity_Success_REGISTER,
    Gender_Success_REGISTER,
    Provider_Success_REGISTER,
    Provider_User_Id_Success_REGISTER,
    Image_Success_REGISTER,
    Active_Success_REGISTER,
    Available_Success_REGISTER
}
